//============================================================================
//
//  IMPACTRO Informática
//  Fábio Ferreira de Souza - 05/12/2002
//
//  Visualizador de arquivos DL1
//
//============================================================================

#define PROGRAMNAME		"ViewDL"

HRESULT WinInit( HINSTANCE hInst, int nCmdShow, HWND* phWnd );
int APIENTRY WinMain( HINSTANCE hInst, HINSTANCE hPrevInst, LPSTR pCmdLine, int nCmdShow );
LRESULT CALLBACK MainWndProc( HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam );

